boklisten/bl-api

- src/bl-error/bl-error-handler.ts
- src/collections/order/operations/place/order-place.operation.ts
There was already a check to prevent a blid from being added to an order if it already belongs to another order, but if the order had been fulfilled (i.e. the blid handed out), the item could be handed out to another person without first being handed in. This commit fixes that by checking whether some blid in an order is not handed in. In that case, it returns an error with code 801 (409 in the HTTP response).
There are some customeritems which do not have blids, which means we cannot prevent those items from being handed out again. However, some research indicates that these are legacy items of which there are exceedingly few which are not handed in (~55 at time of writing).
> fix(order): prevent multiple handouts of a blid

- src/collections/match/helpers/match-finder-2/match-finder.spec.ts
- src/collections/match/helpers/match-finder-2/match-finder.ts
- src/collections/match/helpers/match-finder-2/match-utils.ts
With this change, the MatchFinder is limited to 2 UserMatches per sender or receiver. (A user can have 4 UserMatches if they both send and receive)
Also, made some optimizations to the matching, by calculating for the best possible stand matches early. Thus, we do not need to pass outdatedItems anymore, since the algorithm now finds them by itself. The results of the improvements are in Trello.
To evaluate the tweaking of the algorithm, I used data from all the orders of Boklisten, which I did not want to put in version control 🙃. Therefore, much of the optimisations are not covered by any tests. Aka. no tests fail if you remove them. They do however provide significant matchmaking benefits in real life scenarios.
> feat(MatchFinder): Limit number of UserMatches and optimize matching

- src/bl-error/bl-error-handler.ts
- src/collections/match/operations/match-operation-utils.ts
- src/collections/order/operations/place/order-place.operation.ts
- fix(match-generation): use correct aggregation for senders and receivers
- feat(item return): throw if customerItem part of UserMatch, otherwise update StandMatch with returned item if possible
While working on the logic for updating matches when orders are placed, I noticed I had completely overlooked the aggregation for getting senders and receivers. Using `active: true` is not sufficient at all, we have to use a proper query. (active seems to be true for all customer items 🙃) Therefore, I fixed the aggregations. 🧑‍🔧
Also made some logic to block users from delivering items to stand when those items are are part of a UserMatch.
Lastly, I made logic to update deliveredItems for a standMatch when a match-user delivers an item (of which the item must be part of the StandMatch)
> Update Matches Upon Return And Fix Match Generation Aggregation

- src/collections/order/helpers/order-item-moved-from-order-handler/order-item-moved-from-order-handler.ts
This blocked you when trying to patch an order, eg. updating the
handoutBranch for instance. This check seems redundant, an in opposition
with the normal patch flow that exists within the other collections.
> fix(order-patch): remove unneccecary check for movedtoOrder

- src/collections/order/helpers/order-item-moved-from-order-handler/order-item-moved-from-order-handler.ts
Needed a `String(orderItem.movedToOrder)` since `orderItem.movedToOrder` is stored and read as an objectID, while `orderItemToUpdate.newOrderId` is a String
> fix(order-patch): add missing string conversion in comparison

- src/collections/order/hooks/order.post.hook.spec.ts
- src/collections/order/hooks/order.post.hook.ts
This PR implements a hard block on order creation if the customer details are not set. This is just a reassurance for us that our users are not able in some magical way to order, even though the frontend has been updated so that it should not be possible
> fix(order): block order generation if userDetails are not present

- src/collections/order/helpers/order-item-moved-from-order-handler/order-item-moved-from-order-handler.ts
We had a problem updating multiple orders at the same time, since it tried to access and update the same database object at the simultaneously. So essentially, only one went through, and it threw an error, since one of the promises tried to access a locked object. 
Introduced in https://github.com/boklisten/bl-api/pull/464/commits/c7e003f536c9098251fca00c87174dadcddfd225
> HOTFIX(moved-to-order): update db sequentially

- src/messenger/sms/sms-service.ts
- src/messenger/sms/sms-settings.ts
> feat(sms): Use custom sender name

- package.json
- src/auth/local/local-login.validator.spec.ts
- src/auth/token/token.handler.spec.ts
- src/auth/user/user-provider/user-provider.spec.ts
- src/auth/user/user.handler.spec.ts
- src/auth/user/user.handler.ts
- src/bl-error/bl-error-handler.ts
- src/collections/email-validation/helpers/email-validation.helper.spec.ts
- src/collections/email-validation/helpers/email-validation.helper.ts
- src/collections/email-validation/hooks/email-validation-post.hook.spec.ts
- src/collections/message/hooks/message-post.hook.spec.ts
- src/collections/message/hooks/message-post.hook.ts
- src/collections/order/helpers/order-placed-handler/order-placed-handler.spec.ts
- src/collections/order/helpers/order-placed-handler/order-placed-handler.ts
- src/messenger/email/email-service.ts
- src/messenger/email/order-email/order-email-handler.spec.ts
- src/messenger/email/order-email/order-email-handler.ts
- src/messenger/messenger.ts
- src/messenger/reminder/messenger-reminder.ts
- yarn.lock
- refactor: improve signatures and patterns of message code
- refactor: improve signatures and patterns of message code
- chore: fix randomly failing test by unifying date formatting
- fix(message-post-hook): move sending to before() to only log successful messages
- feat: enable custom SMS reminder text
> feat(message): add support for custom SMS reminder text

- src/collections/customer-item/customer-item.schema.ts
The fact that these values are not initialized as "false" makes some queries not work anymore (since we have queries checking whether these are exlicitly equal to "false", not falsey. Therefore, we need to set these to "false" by default. We also need to apply these defaults to the items in the database that don't have these
> fix(customer-item.schema): reintroduce default false values

- src/collections/invoice/invoice.schema.ts
When we updated Mongoose, it now simply did not add this field as it was not part of the schema. (as it should)
> HOTFIX(invoice): add missing payment field to schema

- package.json
The strict mode TS PR changed the output of the compilation. I was foolish and did not actually build and serve 🤷🏻
> build: use correct dist path

- src/http/http.handler.ts
- src/payment/dibs/dibs-payment.service.ts
This caused payments to fail, as the response was just [Object object] due to the String() conversion. This caused payments to break...
> HOTFIX(http.handler): remove String conversion of response body

- src/collections/match/operations/match-operation-utils.ts
Once the item is transferred, they will have signed anyway, as ordering books makes you sign. We might handle the case where a minor orders and then the guardian does not sign before the match transfer on a later occasion.
> fix(match-operation): add missing pending signature field

- src/collections/match/operations/match-transfer-item.operation.ts
- src/collections/order/operations/place/order-place.operation.ts
- **refactor(match-transfer): fix some ts-ignores**
- **fix(order-place): update correct standmatch if present**
> Update Correct StandMatch When Placing a Match Order

- package.json
- src/collections/match/helpers/match-finder-2/match-finder.spec.ts
- src/collections/match/helpers/match-finder-2/match-finder.ts
- src/collections/match/helpers/match-finder-2/match-testing-utils.ts
- src/collections/match/helpers/match-finder-2/match-utils.ts
- src/collections/match/match.schema.ts
- src/collections/match/operations/match-generate-operation-helper.ts
- src/collections/match/operations/match-generate.operation.ts
- src/collections/match/operations/match-getall-me-operation-helper.ts
- src/collections/match/operations/match-operation-utils.ts
- src/collections/match/operations/match-transfer-item.operation.ts
- src/collections/order/helpers/order-validator/order-item-validator/order-item-validator.spec.ts
- src/collections/order/helpers/order-validator/order-item-validator/order-item-validator.ts
- src/storage/blDocumentStorage.ts
- src/storage/blStorageHandler.ts
- yarn.lock
New features include:
- Blocking matching with oneself, to enable receiving books that you already have
- Add option to be able match all remaining books for senders
- Add option to add extra items to the matches of all receivers. That way, we can enforce certain books for the receivers
- The option to set a custom deadline for certain items part of a match
> Update Match Algorithm

- src/collections/order/operations/place/order-place.operation.ts
Previously, there was a bug where handing out or in multiple items in
one order would cause only one (the last one) to be registered in the
StandMatch. That is now fixed.
> fix: register multiple standmatch items at a time

- src/collections/match/operations/match-getall-me-operation-helper.ts
- src/collections/match/operations/match-getall-me.operation.ts
Some users got a mysterious "Noe har gått galt" screen when we were at Ulleren. This occured due to one of the blids that had been registered as transferred, had later been returned. We discovered this problem when someone first received a blid, then came to the stand to deliver it, because they did not want it after all. The error develops because we used to look up active customer items to find the item ID for a certain blid. The problem with that approach is that when an item is returned, we are unable to get the item ID. Thus, we get an error that ultimately blocks the user from seeing their matches.
This issue has been fixed by looking up items with uniqueitemstorage, which is the sensible thing to do, as that table only maps blId => itemId.
> fix(match-getall-me): lookup with UniqueItems to prevent error with inactive customeritems

- src/collections/order/operations/place/order-place.operation.ts
- tsconfig.json
- **feat(match): change scan feedback**
- **ci(tsconfig): don't error on unused**
- **feat(order): update user matches on handout/-in**
When user matches are unlocked, the books should be shown as properly
handed out/in when the stand takes care of it. Therefore, when the stand
hands out a book, if the receiver was supposed to get it through a
UserMatch, that match will update to show he received the item. However,
the sender who was supposed to deliver it will get the usual warning
that he has to deliver his book even though someone else gave the
receiver a book. Similarly, when the stand accepts a book, if the sender
was supposed to deliver it through a UserMatch, it will update the match
to show that it was delivered. However, the receiver will still see that
they need to get the book. …
> feat(order): update user matches on stand handout/-in

- src/response/se.response.handler.ts
We need to use proper query params for the eventual bl-next switch. This is a prepatory step to enable the switch.
> Use Query Params Instead of Parm Map for auth/token

- .github/workflows/main.yml
- package.json
- src/auth/facebook/facebook.auth.ts
- src/auth/google/google.auth.ts
- src/auth/token/access-token/access-token.secret.ts
- src/auth/token/refresh/refresh-token.secret.ts
- src/collections/delivery/helpers/deliveryBring/bringDelivery.service.ts
- src/collections/delivery/operations/postal-code-lookup.operation.ts
- src/config/api-path.ts
- src/config/environment.ts
- src/logger/logger.ts
- src/messenger/email/email-service.ts
- src/messenger/email/email-settings.ts
- src/messenger/sms/sms-service.ts
- src/payment/dibs/dibs-payment.service.ts
- src/response/se.response.handler.ts
- src/server/server.ts
- yarn.lock
- **refactor(dotenv): use esm import**
- **feat(email-service): setup email templates**
This PR sets up email templating, using SendGrid Dynamic Templates. This means that we can generate the emails in the SendGrid GUI editor, and insert variables, attachments or custom HTML if need be. This approach can let us get rid of bl-email _really_ quickly, as I just made our first template in like 5 minutes, for the email confirmation page. This design is quite simple tho, and we can for sure make something really pretty with their tooling.
> Setup SendGrid Templates
